#include <iostream>
using namespace std;
main()
{
int n1;
int n2;
int n3;
int n4;
int n5;
int n6;
int n7;
int n8;
int n9;
int n10;
int n11;
int n12;
int n13;
int n14;
int n15;
int finalresult;
int X;
int Y;
int Z;
int A;
cout<< "enter the value of n1 "<<endl;
cin>> n1;
cout<< " enter the value of n2 " <<endl;
cin>> n2;
cout<< "enter the value of n3 " <<endl;
cin>> n3;
cout<< "enter the value of n4 " <<endl;
cin>> n4 ;
cout<< "enter the value of n5 " <<endl;
cin>> n5 ;
cout<< "enter the value of n6 " <<endl;
cin>> n6;
cout<< "enter the value of n7 " <<endl;
cin>> n7 ;
cout<< "enter the value of n8 " <<endl;
cin>> n8 ;
cout<< "enter the value of n9 " <<endl;
cin>> n9 ;
cout<< " enter the value of n10 " <<endl;
cin>> n10;
cout<< "enter the value of n11" <<endl;
cin>> n11 ;
cout<< "enter the value of n12 " <<endl;
cin>> n12 ;
cout<< " enter the value of n13 " << endl;
cin>> n13 ;
cout<< " enter the value of n14 " << endl;
cin>> n14 ;
cout<< "enter the value of n15 " <<endl;
cin>> n15 ;
X = n1 + n2 + n3 + n4 + n5 ;
cout<< "X= "<< X <<endl;
Y = n6 * n7 * n8 * n9 * n10;
cout<< " Y= " << Y <<endl;
Z = n11 - n12 - n13 - n14 - n15 ;
cout<< " Z " << Z <<endl;
A = X + Y ;
cout<< " A= " << A <<endl;
finalresult = (X + Y)- Z ;
cout<< "finalresult= " << finalresult <<endl;
}